"""
JARVIS — brain/training_data.py
Comprehensive labeled training dataset for intent classifier.

Stats:
  - 1000+ training examples
  - 30+ intent classes
  - Includes Indian English, casual speech, voice-style phrases
  - Colab-ready: import this file directly in train_colab.py
"""

TRAINING_DATA = [

    # ════════════════════════════════════════════════════════════
    # OPEN APP
    # ════════════════════════════════════════════════════════════
    ("open notepad", "open_app"),
    ("launch spotify", "open_app"),
    ("start chrome", "open_app"),
    ("open calculator", "open_app"),
    ("open vs code", "open_app"),
    ("launch file explorer", "open_app"),
    ("open telegram", "open_app"),
    ("start excel", "open_app"),
    ("open paint", "open_app"),
    ("launch word", "open_app"),
    ("open the camera", "open_app"),
    ("can you open settings", "open_app"),
    ("open task manager", "open_app"),
    ("start vlc", "open_app"),
    ("open discord", "open_app"),
    ("launch brave browser", "open_app"),
    ("open whatsapp desktop", "open_app"),
    ("open snipping tool", "open_app"),
    ("open powerpoint", "open_app"),
    ("launch adobe photoshop", "open_app"),
    ("open zoom", "open_app"),
    ("start microsoft teams", "open_app"),
    ("open google chrome", "open_app"),
    ("launch python idle", "open_app"),
    ("open visual studio", "open_app"),
    ("start android studio", "open_app"),
    ("open postman", "open_app"),
    ("launch docker", "open_app"),
    ("open obsidian", "open_app"),
    ("start notion", "open_app"),
    ("open figma", "open_app"),
    ("launch pycharm", "open_app"),
    ("open steam", "open_app"),
    ("start epic games", "open_app"),
    ("open camera app", "open_app"),
    ("launch mail app", "open_app"),
    ("open maps", "open_app"),
    ("start terminal", "open_app"),
    ("open command prompt", "open_app"),
    ("launch powershell", "open_app"),
    ("open github desktop", "open_app"),
    ("start winrar", "open_app"),
    ("open media player", "open_app"),
    ("launch itunes", "open_app"),
    ("open one drive", "open_app"),
    ("start skype", "open_app"),
    ("open firefox", "open_app"),
    ("launch edge browser", "open_app"),
    ("open opera", "open_app"),
    ("start sublime text", "open_app"),
    ("open atom editor", "open_app"),
    ("launch jupyter notebook", "open_app"),
    ("open anaconda", "open_app"),
    ("start spyder", "open_app"),

    # ════════════════════════════════════════════════════════════
    # CLOSE APP
    # ════════════════════════════════════════════════════════════
    ("close notepad", "close_app"),
    ("kill chrome", "close_app"),
    ("exit spotify", "close_app"),
    ("close the calculator", "close_app"),
    ("quit vs code", "close_app"),
    ("stop notepad", "close_app"),
    ("close this app", "close_app"),
    ("kill task manager", "close_app"),
    ("end excel", "close_app"),
    ("shut down chrome", "close_app"),
    ("close all apps", "close_app"),
    ("close brave", "close_app"),
    ("exit discord", "close_app"),
    ("quit zoom", "close_app"),
    ("close teams", "close_app"),
    ("terminate vlc", "close_app"),
    ("close word", "close_app"),
    ("exit powerpoint", "close_app"),
    ("kill firefox", "close_app"),
    ("close all windows", "close_app"),
    ("end this program", "close_app"),
    ("close the browser", "close_app"),
    ("shut down the app", "close_app"),
    ("force quit chrome", "close_app"),
    ("close everything", "close_app"),

    # ════════════════════════════════════════════════════════════
    # SYSTEM VOLUME
    # ════════════════════════════════════════════════════════════
    ("increase volume", "system_volume"),
    ("volume up", "system_volume"),
    ("turn up the volume", "system_volume"),
    ("make it louder", "system_volume"),
    ("decrease volume", "system_volume"),
    ("volume down", "system_volume"),
    ("lower the volume", "system_volume"),
    ("mute", "system_volume"),
    ("unmute", "system_volume"),
    ("set volume to 50", "system_volume"),
    ("turn the sound up", "system_volume"),
    ("silence the computer", "system_volume"),
    ("raise volume", "system_volume"),
    ("reduce volume", "system_volume"),
    ("sound up please", "system_volume"),
    ("sound down please", "system_volume"),
    ("can you increase the sound", "system_volume"),
    ("make it quieter", "system_volume"),
    ("turn off sound", "system_volume"),
    ("max volume", "system_volume"),
    ("minimum volume", "system_volume"),
    ("speaker off", "system_volume"),
    ("speaker on", "system_volume"),

    # ════════════════════════════════════════════════════════════
    # SYSTEM BRIGHTNESS
    # ════════════════════════════════════════════════════════════
    ("increase brightness", "system_brightness"),
    ("brightness up", "system_brightness"),
    ("make screen brighter", "system_brightness"),
    ("decrease brightness", "system_brightness"),
    ("dim the screen", "system_brightness"),
    ("lower brightness", "system_brightness"),
    ("turn down brightness", "system_brightness"),
    ("set brightness to 80", "system_brightness"),
    ("reduce screen brightness", "system_brightness"),
    ("can you dim the screen", "system_brightness"),
    ("brighten my screen", "system_brightness"),
    ("screen too dark", "system_brightness"),
    ("screen too bright", "system_brightness"),
    ("max brightness", "system_brightness"),
    ("night mode brightness", "system_brightness"),

    # ════════════════════════════════════════════════════════════
    # SCREENSHOT
    # ════════════════════════════════════════════════════════════
    ("take a screenshot", "screenshot"),
    ("capture screen", "screenshot"),
    ("screenshot please", "screenshot"),
    ("grab the screen", "screenshot"),
    ("take a screen capture", "screenshot"),
    ("snap the screen", "screenshot"),
    ("take a picture of screen", "screenshot"),
    ("save screen image", "screenshot"),
    ("print screen", "screenshot"),
    ("capture this screen", "screenshot"),
    ("take screenshot now", "screenshot"),
    ("snap screenshot", "screenshot"),

    # ════════════════════════════════════════════════════════════
    # WEATHER
    # ════════════════════════════════════════════════════════════
    ("what's the weather", "weather"),
    ("how's the weather today", "weather"),
    ("weather in chennai", "weather"),
    ("is it going to rain", "weather"),
    ("what's the temperature", "weather"),
    ("weather forecast", "weather"),
    ("tell me the weather", "weather"),
    ("how hot is it outside", "weather"),
    ("what's the weather like", "weather"),
    ("will it rain today", "weather"),
    ("humidity today", "weather"),
    ("weather update", "weather"),
    ("check the weather", "weather"),
    ("is it sunny today", "weather"),
    ("what is the weather report", "weather"),
    ("temperature outside", "weather"),
    ("should I carry umbrella", "weather"),
    ("how cold is it", "weather"),
    ("any rain expected", "weather"),
    ("weather for tomorrow", "weather"),
    ("weekend weather", "weather"),

    # ════════════════════════════════════════════════════════════
    # NEWS
    # ════════════════════════════════════════════════════════════
    ("what's the news", "news"),
    ("tell me the headlines", "news"),
    ("top stories today", "news"),
    ("any news about technology", "news"),
    ("sports news", "news"),
    ("what's happening in the world", "news"),
    ("breaking news", "news"),
    ("read me the news", "news"),
    ("today's headlines", "news"),
    ("tech news today", "news"),
    ("india news today", "news"),
    ("business news", "news"),
    ("cricket news", "news"),
    ("bollywood news", "news"),
    ("political news", "news"),
    ("international news", "news"),
    ("stock market news", "news"),
    ("what's new today", "news"),
    ("any updates", "news"),
    ("science news", "news"),

    # ════════════════════════════════════════════════════════════
    # YOUTUBE
    # ════════════════════════════════════════════════════════════
    ("play on youtube", "youtube"),
    ("open youtube", "youtube"),
    ("youtube search", "youtube"),
    ("play despacito on youtube", "youtube"),
    ("search youtube for tutorials", "youtube"),
    ("find videos about python", "youtube"),
    ("play music video on youtube", "youtube"),
    ("show me youtube", "youtube"),
    ("youtube coding tutorials", "youtube"),
    ("open youtube and play songs", "youtube"),
    ("play latest songs on youtube", "youtube"),
    ("search for gaming videos youtube", "youtube"),
    ("play lo fi music on youtube", "youtube"),
    ("play arijit singh songs", "youtube"),
    ("youtube shorts", "youtube"),
    ("play motivational videos", "youtube"),
    ("open youtube music", "youtube"),

    # ════════════════════════════════════════════════════════════
    # GOOGLE SEARCH / BROWSER SEARCH
    # ════════════════════════════════════════════════════════════
    ("search for python tutorials", "google_search"),
    ("google how to cook pasta", "google_search"),
    ("search online for laptops", "google_search"),
    ("look up machine learning", "google_search"),
    ("find information about AI", "google_search"),
    ("google search for recipes", "google_search"),
    ("search for best restaurants", "google_search"),
    ("look up the meaning of quantum", "google_search"),
    ("browser search machine learning", "browser_search"),
    ("search in browser for python", "browser_search"),
    ("find in google AI tools", "google_search"),
    ("google iphone 16 price", "google_search"),
    ("search for coding projects", "google_search"),
    ("search how to make biryani", "google_search"),
    ("google maps directions", "google_search"),
    ("search for jobs in hyderabad", "google_search"),
    ("find best colleges in india", "google_search"),
    ("google cricket score", "google_search"),
    ("look up stock prices", "google_search"),
    ("search for python documentation", "google_search"),

    # ════════════════════════════════════════════════════════════
    # WIKIPEDIA / FACTUAL
    # ════════════════════════════════════════════════════════════
    ("tell me about python programming", "wikipedia"),
    ("who is the president of india", "wikipedia"),
    ("tell me about the solar system", "wikipedia"),
    ("who invented the telephone", "wikipedia"),
    ("what is blockchain", "wikipedia"),
    ("history of artificial intelligence", "wikipedia"),
    ("who is narendra modi", "wikipedia"),
    ("explain the big bang theory", "wikipedia"),
    ("what is cryptocurrency", "wikipedia"),
    ("tell me about world war 2", "wikipedia"),
    ("who created python language", "wikipedia"),
    ("what is the speed of light", "wikipedia"),
    ("tell me about india", "wikipedia"),
    ("who is bill gates", "wikipedia"),
    ("what is quantum physics", "wikipedia"),
    ("history of computers", "wikipedia"),
    ("who is virat kohli", "wikipedia"),
    ("what is the internet", "wikipedia"),
    ("tell me about space", "wikipedia"),
    ("who discovered gravity", "wikipedia"),

    # ════════════════════════════════════════════════════════════
    # EMAIL — SEND
    # ════════════════════════════════════════════════════════════
    ("send email to rahul", "send_email"),
    ("compose an email", "send_email"),
    ("write email to boss", "send_email"),
    ("email john saying hello", "send_email"),
    ("send a mail to priya", "send_email"),
    ("draft an email", "send_email"),
    ("send email to professor", "send_email"),
    ("mail my friend", "send_email"),
    ("write a mail saying I'll be late", "send_email"),
    ("compose mail to hr", "send_email"),
    ("send email with attachment", "send_email"),
    ("forward this email", "send_email"),
    ("reply to the last email", "send_email"),
    ("email mom good morning", "send_email"),

    # ════════════════════════════════════════════════════════════
    # EMAIL — READ
    # ════════════════════════════════════════════════════════════
    ("read my emails", "read_email"),
    ("check inbox", "read_email"),
    ("any new emails", "read_email"),
    ("show my emails", "read_email"),
    ("read latest email", "read_email"),
    ("check my mail", "read_email"),
    ("do I have any unread emails", "read_email"),
    ("open my inbox", "read_email"),
    ("read my new messages", "read_email"),
    ("check if I got any mail", "read_email"),
    ("any emails from boss", "read_email"),
    ("read the most recent email", "read_email"),

    # ════════════════════════════════════════════════════════════
    # REMINDER
    # ════════════════════════════════════════════════════════════
    ("remind me to call mom at 5", "reminder"),
    ("set a reminder for meeting", "reminder"),
    ("remind me in 10 minutes", "reminder"),
    ("set alarm for 7 am", "reminder"),
    ("reminder to drink water", "reminder"),
    ("wake me up at 6", "reminder"),
    ("remind me to take medicine", "reminder"),
    ("set reminder for gym at 6 am", "reminder"),
    ("remind me to submit assignment", "reminder"),
    ("set daily reminder for standup", "reminder"),
    ("remind me to pay bills tomorrow", "reminder"),
    ("alert me at 9 pm", "reminder"),
    ("remind me every hour to drink water", "reminder"),
    ("set reminder for mom's birthday", "reminder"),
    ("notify me before the exam", "reminder"),

    # ════════════════════════════════════════════════════════════
    # TIMER
    # ════════════════════════════════════════════════════════════
    ("set timer for 5 minutes", "timer"),
    ("start a countdown", "timer"),
    ("timer for 30 seconds", "timer"),
    ("count down from 10", "timer"),
    ("set a 2 minute timer", "timer"),
    ("start 10 minute timer", "timer"),
    ("30 second countdown", "timer"),
    ("timer for boiling eggs", "timer"),
    ("set pomodoro timer", "timer"),
    ("1 hour timer", "timer"),
    ("15 minute countdown", "timer"),
    ("set stopwatch", "timer"),

    # ════════════════════════════════════════════════════════════
    # WHATSAPP
    # ════════════════════════════════════════════════════════════
    ("message to banty hello", "whatsapp"),
    ("send whatsapp to rahul", "whatsapp"),
    ("text banty saying hi", "whatsapp"),
    ("whatsapp message to mom", "whatsapp"),
    ("send message to priya", "whatsapp"),
    ("message someone on whatsapp", "whatsapp"),
    ("text to sarvani good morning", "whatsapp"),
    ("send a text to ganesh", "whatsapp"),
    ("whatsapp priya I'm coming", "whatsapp"),
    ("send hi to dad on whatsapp", "whatsapp"),
    ("message boss I'll be late", "whatsapp"),
    ("text my friend happy birthday", "whatsapp"),
    ("send good night to mom", "whatsapp"),
    ("whatsapp to college group", "whatsapp"),
    ("message team on whatsapp", "whatsapp"),
    ("send sticker to rahul", "whatsapp"),

    # ════════════════════════════════════════════════════════════
    # TIME & DATE
    # ════════════════════════════════════════════════════════════
    ("what time is it", "time_date"),
    ("tell me the time", "time_date"),
    ("what's the date today", "time_date"),
    ("what day is it", "time_date"),
    ("current time", "time_date"),
    ("today's date", "time_date"),
    ("what is today", "time_date"),
    ("what time is it now", "time_date"),
    ("tell me today's date", "time_date"),
    ("what's the time right now", "time_date"),
    ("is it morning or evening", "time_date"),
    ("what month is it", "time_date"),
    ("what year is it", "time_date"),
    ("how many days until new year", "time_date"),
    ("what day of the week is it", "time_date"),

    # ════════════════════════════════════════════════════════════
    # JOKES
    # ════════════════════════════════════════════════════════════
    ("tell me a joke", "joke"),
    ("say something funny", "joke"),
    ("make me laugh", "joke"),
    ("crack a joke", "joke"),
    ("tell a funny joke", "joke"),
    ("give me a joke", "joke"),
    ("say a programming joke", "joke"),
    ("tell me a dad joke", "joke"),
    ("make me smile", "joke"),
    ("I need a laugh", "joke"),
    ("say something witty", "joke"),
    ("entertain me", "joke"),

    # ════════════════════════════════════════════════════════════
    # MEDIA / SPOTIFY
    # ════════════════════════════════════════════════════════════
    ("play believer on spotify", "media"),
    ("next song", "media"),
    ("skip this track", "media"),
    ("previous song", "media"),
    ("pause the music", "media"),
    ("resume playing", "media"),
    ("play some music", "media"),
    ("stop the song", "media"),
    ("play shape of you", "media"),
    ("skip to next track", "media"),
    ("play sad songs", "media"),
    ("shuffle my playlist", "media"),
    ("play lofi", "media"),
    ("play hip hop", "media"),
    ("play rock music", "media"),
    ("play classical music", "media"),
    ("increase music volume", "media"),
    ("stop music", "media"),
    ("play my liked songs", "media"),
    ("play workout playlist", "media"),
    ("repeat this song", "media"),
    ("play music", "media"),
    ("pause song", "media"),
    ("resume song", "media"),

    # ════════════════════════════════════════════════════════════
    # SHOPPING
    # ════════════════════════════════════════════════════════════
    ("find laptops on amazon", "shopping"),
    ("search flipkart for shoes", "shopping"),
    ("buy headphones on amazon", "shopping"),
    ("compare prices of phones", "shopping"),
    ("shop for watches", "shopping"),
    ("search myntra for shirts", "shopping"),
    ("find deals on flipkart", "shopping"),
    ("book a flight to delhi", "shopping"),
    ("hotel in mumbai", "shopping"),
    ("order food on swiggy", "shopping"),
    ("order pizza on zomato", "shopping"),
    ("buy groceries on blinkit", "shopping"),
    ("search for iphone on amazon", "shopping"),
    ("check price of samsung tv", "shopping"),
    ("book train ticket", "shopping"),
    ("buy books on amazon", "shopping"),
    ("find cheap flights", "shopping"),
    ("search airbnb in goa", "shopping"),
    ("order stationery online", "shopping"),

    # ════════════════════════════════════════════════════════════
    # VISION / SCREEN
    # ════════════════════════════════════════════════════════════
    ("what's on my screen", "vision_screen"),
    ("what am I looking at", "vision_screen"),
    ("describe my screen", "vision_screen"),
    ("what app is open", "vision_screen"),
    ("any errors on screen", "vision_screen"),
    ("what does my screen show", "vision_screen"),
    ("read what's on screen", "vision_screen"),
    ("analyze my screen", "vision_screen"),
    ("what's visible on my desktop", "vision_screen"),
    ("tell me what's on display", "vision_screen"),
    ("scan my screen", "vision_screen"),
    ("what's the error message", "vision_screen"),

    # ════════════════════════════════════════════════════════════
    # FILE OPERATIONS
    # ════════════════════════════════════════════════════════════
    ("open file explorer", "file_open"),
    ("open my documents", "file_open"),
    ("open the downloads folder", "file_open"),
    ("open desktop folder", "file_open"),
    ("open main.py", "file_open"),
    ("open notes.txt", "file_open"),
    ("create a new file", "file_create"),
    ("make a new text file", "file_create"),
    ("write a note", "file_create"),
    ("create a new document", "file_create"),
    ("save my notes", "file_create"),

    # ════════════════════════════════════════════════════════════
    # CODE RUNNER
    # ════════════════════════════════════════════════════════════
    ("write code to print hello", "code_run"),
    ("create hello.py", "code_run"),
    ("write a python script", "code_run"),
    ("generate code for calculator", "code_run"),
    ("write code to list files", "code_run"),
    ("create main.py with hello world", "code_run"),
    ("write a script to rename files", "code_run"),
    ("generate python code", "code_run"),
    ("code to get current time", "code_run"),
    ("write a function to add numbers", "code_run"),
    ("create index.html", "code_run"),
    ("write javascript code", "code_run"),
    ("generate html template", "code_run"),
    ("run the code", "code_run"),
    ("execute the script", "code_run"),
    ("run it", "code_run"),
    ("run main.py", "code_run"),
    ("execute the file", "code_run"),
    ("run this program", "code_run"),

    # ════════════════════════════════════════════════════════════
    # SHUTDOWN / SYSTEM
    # ════════════════════════════════════════════════════════════
    ("shutdown the computer", "shutdown"),
    ("restart my laptop", "shutdown"),
    ("reboot the system", "shutdown"),
    ("turn off the computer", "shutdown"),
    ("put computer to sleep", "shutdown"),
    ("hibernate the system", "shutdown"),
    ("cancel shutdown", "shutdown"),
    ("logout", "shutdown"),
    ("sign out", "shutdown"),
    ("restart windows", "shutdown"),
    ("power off", "shutdown"),
    ("sleep mode", "shutdown"),

    # ════════════════════════════════════════════════════════════
    # STOP / QUIT JARVIS
    # ════════════════════════════════════════════════════════════
    ("stop jarvis", "stop"),
    ("quit", "stop"),
    ("exit", "stop"),
    ("goodbye", "stop"),
    ("shut down jarvis", "stop"),
    ("bye bye", "stop"),
    ("go to sleep jarvis", "stop"),
    ("that's all for now", "stop"),
    ("I'm done", "stop"),
    ("close jarvis", "stop"),
    ("turn off jarvis", "stop"),
    ("jarvis stop", "stop"),
    ("ok goodbye", "stop"),
    ("see you later", "stop"),
    ("bye jarvis", "stop"),

    # ════════════════════════════════════════════════════════════
    # RESET CONVERSATION
    # ════════════════════════════════════════════════════════════
    ("reset conversation", "reset"),
    ("clear chat", "reset"),
    ("start over", "reset"),
    ("forget everything", "reset"),
    ("new conversation", "reset"),
    ("clear memory", "reset"),
    ("reset jarvis", "reset"),
    ("fresh start", "reset"),
    ("wipe conversation", "reset"),
    ("clear history", "reset"),

    # ════════════════════════════════════════════════════════════
    # GREETING
    # ════════════════════════════════════════════════════════════
    ("hello jarvis", "greeting"),
    ("hi", "greeting"),
    ("hey", "greeting"),
    ("good morning", "greeting"),
    ("good evening", "greeting"),
    ("how are you", "greeting"),
    ("what's up", "greeting"),
    ("hello", "greeting"),
    ("hey jarvis", "greeting"),
    ("good afternoon jarvis", "greeting"),
    ("good night", "greeting"),
    ("hi there", "greeting"),
    ("hello hello", "greeting"),
    ("are you there", "greeting"),
    ("wake up jarvis", "greeting"),
    ("namaste", "greeting"),
    ("hey buddy", "greeting"),

    # ════════════════════════════════════════════════════════════
    # MEMORY / PERSONAL FACTS
    # ════════════════════════════════════════════════════════════
    ("my name is srini", "memory"),
    ("remember my name", "memory"),
    ("my favourite color is blue", "memory"),
    ("save this information", "memory"),
    ("remember that I like cricket", "memory"),
    ("my birthday is on april 10", "memory"),
    ("I study computer science", "memory"),
    ("remember I prefer dark mode", "memory"),
    ("my phone number is", "memory"),
    ("save my address", "memory"),
    ("what do you remember about me", "memory"),
    ("what do you know about me", "memory"),
    ("do you remember what I told you", "memory"),
    ("forget what I said earlier", "memory"),
    ("update my information", "memory"),
    ("my favourite food is biryani", "memory"),
    ("I live in hyderabad", "memory"),
    ("remember that I wake up at 6am", "memory"),

    # ════════════════════════════════════════════════════════════
    # CALENDAR
    # ════════════════════════════════════════════════════════════
    ("add meeting tomorrow at 3pm", "calendar"),
    ("schedule exam on monday", "calendar"),
    ("add event birthday party", "calendar"),
    ("create calendar event", "calendar"),
    ("what's my schedule today", "calendar"),
    ("what do I have tomorrow", "calendar"),
    ("what's happening this week", "calendar"),
    ("show my calendar", "calendar"),
    ("what's my next event", "calendar"),
    ("do I have anything today", "calendar"),
    ("cancel my 3pm meeting", "calendar"),
    ("delete the exam event", "calendar"),
    ("schedule appointment at 5pm", "calendar"),
    ("add dentist appointment friday", "calendar"),
    ("what events do I have", "calendar"),
    ("show all events", "calendar"),
    ("schedule class on tuesday", "calendar"),
    ("add gym session at 6am", "calendar"),

    # ════════════════════════════════════════════════════════════
    # GENERAL CHAT (fallback to AI)
    # ════════════════════════════════════════════════════════════
    ("what is the meaning of life", "chat"),
    ("write me a poem", "chat"),
    ("explain relativity", "chat"),
    ("help me with my homework", "chat"),
    ("what do you think about AI", "chat"),
    ("can you help me code", "chat"),
    ("translate hello to spanish", "chat"),
    ("summarize this for me", "chat"),
    ("what is love", "chat"),
    ("tell me something interesting", "chat"),
    ("how does electricity work", "chat"),
    ("give me study tips", "chat"),
    ("help me write a cover letter", "chat"),
    ("what are the best programming languages", "chat"),
    ("suggest a good book", "chat"),
    ("how to improve my english", "chat"),
    ("tips for healthy life", "chat"),
    ("best way to learn machine learning", "chat"),
    ("help me plan my week", "chat"),
    ("write a story", "chat"),
    ("what should I eat today", "chat"),
    ("help me debug this code", "chat"),
    ("explain neural networks simply", "chat"),
    ("how to start a startup", "chat"),
    ("tips to wake up early", "chat"),
    ("motivate me", "chat"),
    ("I feel bored", "chat"),
    ("let's talk", "chat"),
    ("say something inspiring", "chat"),
    ("what's new in technology", "chat"),
    ("tell me an interesting fact", "chat"),
    ("what's your favourite movie", "chat"),
    ("can you be my friend", "chat"),
    ("what can you do", "chat"),
    ("how smart are you", "chat"),
    ("are you better than siri", "chat"),
    ("are you like chatgpt", "chat"),
    ("tell me about yourself", "chat"),
    ("what are your capabilities", "chat"),
    ("how were you made", "chat"),
]
